nav:
  - index.md
  - Recommended Setup: recommended-setup.md
  - Built-in Toolsets: builtin-toolsets
  - HTTP Connectors: api-toolsets.md
  - Custom Toolsets: custom-toolsets.md
  - MCP Servers: remote-mcp-servers.md
