nav:
  - index.md
  - Latest Results: latest-results.md
  - History: history
  - Running Evaluations: running-evals.md
  - Adding New Evaluations: adding-evals.md
  - Benchmarking New Models: benchmarking-new-models.md
  - Reporting with Braintrust: reporting.md
