nav:
    - CLI: cli-installation.md
    - Web UI (3rd party): ui-installation.md
    - Slack Bot (3rd party): slack-installation.md
    - Backstage (3rd party): backstage-integration.md
    - K9s: k9s-installation.md
    - Helm Chart: kubernetes-installation.md
    - Python SDK: python-installation.md
